### ISSUE TITLE
[BUG-adminverrrb] <title>

### ISSUE THREAD

**Issue by Verrrb** [slackapi/tasks-app#87]
### Is there an existing issue for this?

- [X] I have searched for any related issues and avoided creating a duplicate issue.

### Have you read our code of conduct?

- [X] I have read and agree to the code of conduct

### Current Behavior

Throwing attached error when running app.js with node. Not sure if this helps but also got some errors during the npm installation. Can you please help me here, I am trying to figure out what I am not getting right.

### Expected Behavior

Work through like it's shown in the demo here. It's also missing the overall node.js folder on my end compared to the video https://www.youtube.com/watch?v=q3SBz_eqOq0&list=PLWlXaxtQ7fUb0B4uNTKirvrQ0JOTCBFae&index=8

### Steps To Reproduce

1. running node v16.13.1
2. using visual code studio
3. have sqlite3 install globally
4. I am not really technically adept so not sure what else may help you here.

### Environment

```markdown
- OS: Windows 10 build 19043.1348
- Language version: Node v16.13.1
```

### Anything else?

PS C:\apps\tasks-app> node app.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- C:\apps\tasks-app\app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\apps\tasks-app\app.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\apps\\tasks-app\\app.js' ]

**Comment by colmdoyle** [comment]
Hmm, that's not right. We'll look into it.

**Comment by Verrrb** [comment]
Thanks, appreciate it :)

**Comment by colmdoyle** [comment]
Well error 2 is expected as a consequence of error 1, but let me spend some time figuring out why error 1 is happening.

**Comment by Verrrb** [comment]
Thanks for the clarity there, I assume that's because we are building the node app right before error 1 is printed. Would that be correct? I hope my notifications are not inconvenient, just trying to figure out some of these things the first time.

**Comment by colmdoyle** [comment]
Error one happens after you run `npm install` right? It _looks_ like there's an issue with building the dependencies.

I don't have a windows machine to debug right now, but some google-fu leads me to [this](https://stackoverflow.com/questions/35293117/npm-install-that-requires-node-gyp-fails-on-windows)

**Comment by Verrrb** [comment]
Yes, error 1 happens after running `npm install` and that's one of the link I searched up, but just wasn't sure that would be the right one. Let me try following this and get back to you, if that's not a problem.

**Comment by amarinelli** [comment]
@Verrrb I am using Windows so @colmdoyle asked me to take a look. By no means an expert here, but I had similar errors and eventually got things working. Can you try the following?

- [Install Python 3.9.x](https://www.python.org/downloads/windows/)
  - `node-gyp` wants one of: v3.6, v3.7, v3.8, or v3.9. ([ref](https://github.com/nodejs/node-gyp#configuring-python-dependency)).
  - I happen to be using `3.9.5` on my machine.
- Install the _Visual C++ build tools_ workload using the [Visual Studio Installer](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools). Within the installer, the version I installed is within the Workloads tab and is actually labelled _Desktop development with C++_.
  - There are several optional components selected by default. I left this as is since we likely need `MSVC v142 - VS 2019 ...` to be installed.
  - A computer restart will be required once the install has completed.
- In cmd or Windows Terminal, run `npm config set msvs_version 2019`.
  - The [node-gyp installation instructions](https://github.com/nodejs/node-gyp#on-windows) suggest differently, but the 2017 version (which is in the optional section of the VS Installer) did not work for me.
- `npm install` in your `tasks-app` working directory to see if it completes without error.

**Comment by Verrrb** [comment]
> @Verrrb I am using Windows so @colmdoyle asked me to take a look. By no means an expert here, but I had similar errors and eventually got things working. Can you try the following?
> 
> * [Install Python 3.9.x](https://www.python.org/downloads/windows/)
>   
>   * `node-gyp` wants one of: v3.6, v3.7, v3.8, or v3.9. ([ref](https://github.com/nodejs/node-gyp#configuring-python-dependency)).
>   * I happen to be using `3.9.5` on my machine.
> * Install the _Visual C++ build tools_ workload using the [Visual Studio Installer](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools). Within the installer, the version I installed is within the Workloads tab and is actually labelled _Desktop development with C++_.
>   
>   * There are several optional components selected by default. I left this as is since we likely need `MSVC v142 - VS 2019 ...` to be installed.
>   * A computer restart will be required once the install has completed.
> * In cmd or Windows Terminal, run `npm config set msvs_version 2019`.
>   
>   * The [node-gyp installation instructions](https://github.com/nodejs/node-gyp#on-windows) suggest differently, but the 2017 version (which is in the optional section of the VS Installer) did not work for me.
> * `npm install` in your `tasks-app` working directory to see if it completes without error.

Apologies I was away for the weekend will be looking at this today. Thanks for sharing this, will update the thread accordingly.

**Comment by PrestonWinstead** [comment]
I'm seeing this same error on a Mac. Running Monterey 12.6, still on an Intel processor. Tried several versions of Node, since I see that's an issue for lots of people. I've tried the suggestions that are relevant to Mac here (mostly making sure that Python is updated, but also tried `npm install --build-from-resource` and other suggestions I've found on various StackOverflow conversations), but still no luck. Here's my stack trace. Anyone have any suggestions? 
Also, I did try following their warning about `node-pre-gyp` being deprecated, but still get it even after I've made sure to uninstall that everywhere. 

```
➜  node-tasks-app git:(main) ✗ npm install
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
npm ERR! Failed to execute '/Users/prestonwinstead/.nvm/versions/node/v14.15.4/bin/node /Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@14.15.4 | darwin | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@14.15.4 | darwin | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@14.15.4 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "/usr/local/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /usr/local/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/prestonwinstead/Library/Caches/node-gyp/14.15.4/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/prestonwinstead/Library/Caches/node-gyp/14.15.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/prestonwinstead/Library/Caches/node-gyp/14.15.4/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR!
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR!
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR!
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@14.15.4 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/prestonwinstead/.nvm/versions/node/v14.15.4/bin/node" "/Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
npm ERR! gyp ERR! cwd /Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3
npm ERR! gyp ERR! node -v v14.15.4
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/prestonwinstead/.nvm/versions/node/v14.15.4/bin/node /Users/prestonwinstead/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/prestonwinstead/.nvm/versions/node/v14.15.4/bin/node" "/Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/prestonwinstead/Development/Websites/node-tasks-app/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v14.15.4
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prestonwinstead/.npm/_logs/2022-11-11T14_29_25_896Z-debug-0.log
```

**Comment by PrestonWinstead** [comment]
9 minutes later, commenting to say that I figured it out. I updated all of the dependencies in the `package.json` to the latest versions, and it built without an issue.

**Comment by kaoboy** [comment]
Thanks @PrestonWinstead , had the same issue. Updated `package.json` and it compiles. However, when I try to create a new task I get the following errors
<img width="1017" alt="Screenshot 2023-01-14 at 5 33 29 PM" src="https://user-images.githubusercontent.com/1243442/212459322-d34bc40d-62cb-443a-9978-39725d8cc9e2.png">

**Comment by danjhd** [comment]
Again confirmed on Windows i ran `npx npm-check-updates -u` before `npm install` and then once i ran `npm install` this problem was resolved.
